version: '3'
services:

  composer:
    image: composer:2
    volumes:
      - .:/var/www
    working_dir: /var/www

  php-7.3:
    image: php:7.3-cli-alpine
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: vendor/bin/phpunit

  php-7.4:
    image: php:7.4-cli-alpine
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: vendor/bin/phpunit

  php-8.0:
    image: php:8.0-cli-alpine
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: vendor/bin/phpunit

  php-8.1:
    image: php:8.1-cli-alpine
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: vendor/bin/phpunit
